import { describe, it, expect } from "vitest"
import { spawnSync } from "node:child_process"
import { promises as fs } from "node:fs"

const VERSION_PATH = "src/version.ts"

describe("scripts/build-version", () => {
  it("regenerates src/version.ts from the committed spec", async () => {
    // Replace version.ts with a sentinel; running the script should overwrite
    // it with a real header (and a stable VERSION value from package.json).
    await fs.writeFile(VERSION_PATH, "// sentinel\n")
    const result = spawnSync("npx", ["tsx", "scripts/build-version.ts"], {
      encoding: "utf8",
      shell: true,
    })
    expect(result.status).toBe(0)
    const body = await fs.readFile(VERSION_PATH, "utf8")
    expect(body).toContain("AUTO-GENERATED by scripts/build-version.ts")
    expect(body).toMatch(/export const VERSION = "/)
    expect(body).toMatch(/export const SPEC_SHA = "[a-f0-9]{8}"/)
    expect(body).toMatch(/export const API_BASE = "https:\/\/api\.wspc\.ai"/)
  })
})
