import { createHash } from "node:crypto"
import { describe, expect, it } from "vitest"
import {
  STUB_SPEC_SHA,
  specShaPrefix,
  versionFileBody,
} from "../scripts/version-file.js"

describe("version file helpers", () => {
  it("computes the sha256 prefix used for SPEC_SHA", () => {
    const body = "{\"openapi\":\"3.1.0\"}"

    expect(specShaPrefix(body)).toBe(
      createHash("sha256").update(body).digest("hex").slice(0, 8),
    )
  })

  it("builds the exact version file body", () => {
    expect(
      versionFileBody({
        generatedBy: "scripts/test.ts",
        packageVersion: "1.2.3",
        specSha: STUB_SPEC_SHA,
        fetchedAt: new Date("2026-05-26T10:00:00Z"),
        apiBase: "https://api.wspc.ai",
      }),
    ).toBe(
      [
        "// AUTO-GENERATED by scripts/test.ts — DO NOT EDIT",
        "export const VERSION = \"1.2.3\"",
        "export const SPEC_SHA = \"00000000\"",
        "export const SPEC_FETCHED_AT = \"2026-05-26T10:00:00.000Z\"",
        "export const API_BASE = \"https://api.wspc.ai\"",
        "",
      ].join("\n"),
    )
  })
})
