// scripts/build-version.ts
//
// Regenerates `src/version.ts` from the locally-committed
// `spec/openapi.json` — no network access. Runs via the `prepare` lifecycle
// after `npm install` / `npm ci` so consumers, CI, and a fresh clone all get
// the import target `src/cli.ts` and `src/index.ts` expect; `sync-spec` then
// overwrites the same file when actually pulling from prod.
//
// This exists because `src/version.ts` is gitignored (untracked since
// fix(release): auto-rebuild on npm publish + untrack src/version.ts), and
// CI doesn't have network access to call sync-spec.
import { promises as fs } from "node:fs"
import { createHash } from "node:crypto"
import { fileURLToPath } from "node:url"
import { join } from "node:path"

const ROOT = fileURLToPath(new URL("..", import.meta.url))
const SPEC_PATH = join(ROOT, "spec/openapi.json")
const VERSION_PATH = join(ROOT, "src/version.ts")
const PACKAGE_PATH = join(ROOT, "package.json")
const DEFAULT_API_BASE = "https://api.wspc.ai"

async function main(): Promise<void> {
  let spec: string
  try {
    spec = await fs.readFile(SPEC_PATH, "utf8")
  } catch (err) {
    // First-ever clone where spec hasn't been seeded yet — write a stub so
    // typecheck still runs; sync-spec will fill in real values later.
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      await writeVersion({ sha: "00000000", apiBase: DEFAULT_API_BASE })
      console.log("✓ wrote src/version.ts (stub — run `npm run sync-spec` to fetch real spec)")
      return
    }
    throw err
  }
  const sha = createHash("sha256").update(spec).digest("hex").slice(0, 8)
  await writeVersion({ sha, apiBase: DEFAULT_API_BASE })
  console.log(`✓ wrote src/version.ts (sha=${sha}, from local spec)`)
}

async function writeVersion(opts: { sha: string; apiBase: string }): Promise<void> {
  const pkg = JSON.parse(await fs.readFile(PACKAGE_PATH, "utf8")) as { version: string }
  const body = [
    "// AUTO-GENERATED by scripts/build-version.ts — DO NOT EDIT",
    `export const VERSION = ${JSON.stringify(pkg.version)}`,
    `export const SPEC_SHA = ${JSON.stringify(opts.sha)}`,
    `export const SPEC_FETCHED_AT = ${JSON.stringify(new Date().toISOString())}`,
    `export const API_BASE = ${JSON.stringify(opts.apiBase)}`,
    "",
  ].join("\n")
  await fs.mkdir(join(ROOT, "src"), { recursive: true })
  await fs.writeFile(VERSION_PATH, body)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
