// scripts/build-version.ts
//
// Regenerates `<rootDir>/src/version.ts` from the locally-committed
// `<rootDir>/spec/openapi.json` — no network access. Runs via the `prepare`
// npm lifecycle after every install so consumers, CI, and a fresh clone all
// get the import target `src/cli.ts` / `src/index.ts` expect; `sync-spec`
// then overwrites the same file when actually pulling from prod.
//
// This exists because `src/version.ts` is gitignored (untracked since
// fix(release): auto-rebuild on npm publish + untrack src/version.ts), and
// CI doesn't have network access to call sync-spec.
import { promises as fs } from "node:fs"
import { createHash } from "node:crypto"
import { fileURLToPath } from "node:url"
import { join } from "node:path"

const DEFAULT_API_BASE = "https://api.wspc.ai"
const STUB_SHA = "00000000"

export interface BuildVersionOptions {
  rootDir: string
  apiBase?: string
  now?: () => Date
}

export interface BuildVersionResult {
  /** sha256 prefix derived from the spec, or `"00000000"` when the spec is missing. */
  sha: string
  /** True if no spec was present and a stub file was written instead. */
  stubbed: boolean
}

export async function buildVersion(opts: BuildVersionOptions): Promise<BuildVersionResult> {
  const { rootDir } = opts
  const apiBase = opts.apiBase ?? DEFAULT_API_BASE
  const now = opts.now ?? (() => new Date())
  const pkg = JSON.parse(await fs.readFile(join(rootDir, "package.json"), "utf8")) as {
    version: string
  }

  let sha = STUB_SHA
  let stubbed = true
  try {
    const spec = await fs.readFile(join(rootDir, "spec/openapi.json"), "utf8")
    sha = createHash("sha256").update(spec).digest("hex").slice(0, 8)
    stubbed = false
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err
    // First-ever clone where spec hasn't been seeded yet — write a stub so
    // typecheck still runs; sync-spec will fill in real values later.
  }

  const versionPath = join(rootDir, "src/version.ts")
  const body = [
    "// AUTO-GENERATED by scripts/build-version.ts — DO NOT EDIT",
    `export const VERSION = ${JSON.stringify(pkg.version)}`,
    `export const SPEC_SHA = ${JSON.stringify(sha)}`,
    `export const SPEC_FETCHED_AT = ${JSON.stringify(now().toISOString())}`,
    `export const API_BASE = ${JSON.stringify(apiBase)}`,
    "",
  ].join("\n")
  await fs.mkdir(join(rootDir, "src"), { recursive: true })
  await fs.writeFile(versionPath, body)
  return { sha, stubbed }
}

// CLI entry — only runs when invoked directly (e.g. via the `prepare` script),
// not when this module is imported by tests.
if (fileURLToPath(import.meta.url) === process.argv[1]) {
  const rootDir = fileURLToPath(new URL("..", import.meta.url))
  const { sha, stubbed } = await buildVersion({ rootDir })
  if (stubbed) {
    console.log("✓ wrote src/version.ts (stub — run `npm run sync-spec` to fetch real spec)")
  } else {
    console.log(`✓ wrote src/version.ts (sha=${sha}, from local spec)`)
  }
}
