// scripts/sync-spec.ts
import { promises as fs } from "node:fs"
import { createHash } from "node:crypto"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const DEFAULT_URL = "https://api.wspc.ai/openapi.json"

export interface SyncSpecOptions {
  url?: string
  packageVersion: string
  rootDir: string
  fetchImpl?: typeof fetch
  now?: () => Date
}

export async function syncSpec(opts: SyncSpecOptions): Promise<void> {
  const url = opts.url ?? DEFAULT_URL
  const fetchImpl = opts.fetchImpl ?? fetch
  const now = opts.now ?? (() => new Date())

  const res = await fetchImpl(url)
  if (!res.ok) throw new Error(`sync-spec: GET ${url} -> ${res.status}`)
  const body = await res.text()
  const specPath = join(opts.rootDir, "spec/openapi.json")
  await fs.mkdir(dirname(specPath), { recursive: true })
  await fs.writeFile(specPath, body)

  const sha = createHash("sha256").update(body).digest("hex").slice(0, 8)
  const baseUrl = new URL(url).origin

  const versionPath = join(opts.rootDir, "src/version.ts")
  await fs.mkdir(dirname(versionPath), { recursive: true })
  const versionTs = [
    "// AUTO-GENERATED by scripts/sync-spec.ts — DO NOT EDIT",
    `export const VERSION = ${JSON.stringify(opts.packageVersion)}`,
    `export const SPEC_SHA = ${JSON.stringify(sha)}`,
    `export const SPEC_FETCHED_AT = ${JSON.stringify(now().toISOString())}`,
    `export const API_BASE = ${JSON.stringify(baseUrl)}`,
    "",
  ].join("\n")
  await fs.writeFile(versionPath, versionTs)
}

// CLI entry
if (fileURLToPath(import.meta.url) === process.argv[1]) {
  const pkg = JSON.parse(await fs.readFile(new URL("../package.json", import.meta.url), "utf8"))
  await syncSpec({
    packageVersion: pkg.version,
    rootDir: fileURLToPath(new URL("..", import.meta.url)),
  })
  console.log("✓ spec/openapi.json + src/version.ts updated")
}
