import { createHash } from "node:crypto"
import { promises as fs } from "node:fs"
import { dirname, join } from "node:path"

export const STUB_SPEC_SHA = "00000000"

export interface VersionFileArgs {
  generatedBy: string
  packageVersion: string
  specSha: string
  fetchedAt: Date
  apiBase: string
}

export function specShaPrefix(specBody: string): string {
  return createHash("sha256").update(specBody).digest("hex").slice(0, 8)
}

export function versionFileBody(args: VersionFileArgs): string {
  return [
    `// AUTO-GENERATED by ${args.generatedBy} — DO NOT EDIT`,
    `export const VERSION = ${JSON.stringify(args.packageVersion)}`,
    `export const SPEC_SHA = ${JSON.stringify(args.specSha)}`,
    `export const SPEC_FETCHED_AT = ${JSON.stringify(args.fetchedAt.toISOString())}`,
    `export const API_BASE = ${JSON.stringify(args.apiBase)}`,
    "",
  ].join("\n")
}

export async function writeVersionFile(
  rootDir: string,
  args: VersionFileArgs,
): Promise<void> {
  const versionPath = join(rootDir, "src/version.ts")
  await fs.mkdir(dirname(versionPath), { recursive: true })
  await fs.writeFile(versionPath, versionFileBody(args))
}
