// AUTO-GENERATED by scripts/sync-spec.ts — DO NOT EDIT
export const VERSION = "0.0.0"
export const SPEC_SHA = "04c66436"
export const SPEC_FETCHED_AT = "2026-05-26T11:44:34.992Z"
export const API_BASE = "https://api.wspc.ai"
